### ISSUE TITLE
Enable saving progress while grading

### ISSUE THREAD

**Issue by JustinSo1** [tedlasai/GradeHelper#3]
## Introduction:

Progress within the grading process needs to be saved and when later picked up, the program will resume at the same spot.

## Acceptance criteria:

1. The window needs to be able to save the student’s grade when the “Submit Grades” button is clicked.
1. This feature needs to write out grades to each student folder in a csv file per student
1. This feature needs to be tested (e.g unit tests)
1. This feature needs to be able to work with the rest of the program

**Comment by itsianmac** [comment]
This looks to be solved in the PR for #2

**Comment by JustinSo1** [comment]
@itsianmac this issue deals making that "gradehelper.csv" file while PR #4 dealing with #2 just checks for the existence of that file. My bad I should have wrote the issue clearer.

**Comment by itsianmac** [comment]
So not included in description for #2 but solved in PR #4? The version I am running from that branch saves the CSV's to each student directory.

**Comment by JustinSo1** [comment]
Discussed offline in a call. The submitGrade() functionality from the current master branch already has a solution for saving the gradeHelper.csv file
